name: intraspca_dandi_explorer
dependencies:
  - python=3.11
  # bind tornado version (websocket problems)
  - h5py
  - scipy
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - scikit-learn
  - pandas
  